name: intl
version: 0.18.1-dev
description: >-
  Contains code to deal with internationalized/localized messages, date and
  number formatting and parsing, bi-directional text, and other
  internationalization issues.
repository: https://github.com/dart-lang/intl

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  clock: ^1.1.2
  meta: ^1.16.0
  path: ^1.9.1

dev_dependencies:
  benchmark_harness: ^2.3.1
  ffi: ^2.1.3
  fixnum: ^1.1.1
  js: ^0.7.1
  lints: '>=1.0.0 <3.0.0'
  test: ^1.25.8
